### ISSUE TITLE
Running the example test.js fails

### ISSUE THREAD

**Issue by esskar** [pmalhaire/xk6-mqtt#12]
Hi,

i tried to run the test example but i get the following error

````
          /\      |‾‾| /‾‾/   /‾‾/
     /\  /  \     |  |/  /   /  /
    /  \/    \    |     (   /   ‾‾\
   /          \   |  |\  \ |  (‾)  |
  / __________ \  |__| \__\ \_____/ .io

ERRO[0000] TypeError: Value is not an object: undefined
        at file:///C:/Users/esskar/test.js:42:16(88)  hint="script exception"
```

Line 42 is `let publisher = new mqtt.Client(`

Have i missed something?

**Comment by pmalhaire** [comment]
Are you run the command with xk6 or your own built k6 ?

You need to add this extension to k6 see the README.md file at the root of the repo.

**Comment by esskar** [comment]
I compiled everything and use the K6.exe from that compilation. I am running on windows.

**Comment by pmalhaire** [comment]
I unfortunately don't have a windows machine to test this. The message you have means that the JS object of the extension is not available.

**Comment by pmalhaire** [comment]
@esskar do you have a running mqtt server ?

**Comment by pmalhaire** [comment]
Coding since I could not reproduce, reopen in case

**Comment by pmalhaire** [comment]
Can you provide the test command used and thé platfom so I can reproduce your issue ?

**Comment by pmalhaire** [comment]
Closing as no response
