### ISSUE TITLE
TypeError: Value is not an object: undefined

### ISSUE THREAD

**Issue by samerhijazi** [pmalhaire/xk6-mqtt#14]
Hi,
i'am trying the example code from:
https://github.com/pmalhaire/xk6-mqtt/blob/main/examples/test_ssl.js

and I am getting the error "TypeError: Value is not an object: undefined" from the line 49 "**let publisher = new mqtt.Client(**"

Thanks for your help
Samer

**Comment by pmalhaire** [comment]
Can you provide the config you are using and thé command you use ?

**Comment by gajownikp** [comment]
> Hi, i'am trying the example code from: https://github.com/pmalhaire/xk6-mqtt/blob/main/examples/test_ssl.js
> 
> and I am getting the error "TypeError: Value is not an object: undefined" from the line 49 "**let publisher = new mqtt.Client(**"
> 
> Thanks for your help Samer
Hello,

I have same issue 
run it with command:
`./k6 run  --vus 50 --duration 10s examples/test.js`

**Comment by samerhijazi** [comment]
Hallo,
I use the example file, just changed the cert location. Here are the commands:

$ ./k6 version
k6 v0.38.0 ((devel), go1.19.3, darwin/arm64)

$ ./k6 run test_ssl.js

          /\      |‾‾| /‾‾/   /‾‾/   
     /\  /  \     |  |/  /   /  /    
    /  \/    \    |     (   /   ‾‾\  
   /          \   |  |\  \ |  (‾)  | 
  / __________ \  |__| \__\ \_____/ .io

ERRO[0000] TypeError: Value is not an object: undefined
        at file:///Users/samer/test_ssl.js:49:16(101)  hint="script exception"

**Comment by gajownikp** [comment]
@samerhijazi are you using this command to build binary
`xk6 build --with github.com/pmalhaire/xk6-mqtt@latest`

**Comment by samerhijazi** [comment]
@gajownikp : yes as described in the instructions.

**Comment by gajownikp** [comment]
Binary is created with tag 0.38 (latest one)
try this (as workaround):
`xk6 build --with github.com/pmalhaire/xk6-mqtt@f9d21adf`
It works for my mac and GHA
@pmalhaire please add new tag to repo

**Comment by samerhijazi** [comment]
Workaround works. Thanks @gajownikp Thanks @pmalhaire for the code.

**Comment by pmalhaire** [comment]
I'll add a New tag then

**Comment by pmalhaire** [comment]
New tag added
