### ISSUE TITLE
Needed to maintain listing in k6 Extensions Registry

### ISSUE THREAD

**Issue by javaducky** [pmalhaire/xk6-mqtt#16]
We've recently updated the requirements for maintaining an extension within the listing on our site. As such, please address the following items to maintain your listing within the registry:

* requires at least one versioned release
* needs to build with a recent version of k6; minimum v0.43

For more information on these and other listing requirements, please take a look at the [registry requirements](https://k6.io/docs/extensions/explanations/about-the-extensions-registry/).

**Comment by pmalhaire** [comment]
@javaducky done and updated README

**Comment by pmalhaire** [comment]
Release : 

- https://github.com/pmalhaire/xk6-mqtt/releases/tag/v0.39.2
- builds with k6 v0.43

**Comment by javaducky** [comment]
@pmalhaire thank you for looking into this. Could you update the [`go.mod`](https://github.com/pmalhaire/xk6-mqtt/blob/main/go.mod#L10) to require a recent version of k6? Latest release of k6 is v0.45.0, but minimum requirement is v0.43.0.

**Comment by pmalhaire** [comment]
updated go.mod in `main` branch to require k6 `v0.45.0`
