### ISSUE TITLE
Metric names should change "." to "_"

### ISSUE THREAD

**Issue by rgordill** [pmalhaire/xk6-mqtt#21]
There are some warnings regarding prometheus metric name compliance (https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels): 

time="2023-09-13T17:18:01Z" level=warning msg="Metric name should only include ASCII letters, numbers and underscores. This name will stop working in k6 v0.48.0 (around December 2023)." name=mqtt.sent.messages.count

**Comment by pmalhaire** [comment]
Thank you for the MR. It's a breaking change existing usage will be impacted. I have to choose if I make it the default and drop the old name or make it optionnal.

**Comment by rgordill** [comment]
As the log says, the metrics with "." will stop working around december this year, so I guess there is little value in keeping them for just three more months. Anyway, we need the "_" for the prometheus metrics,
