### ISSUE TITLE
Invalid metric name: 'mqtt.sent.bytes' with latest xk6

### ISSUE THREAD

**Issue by clarkbynum** [pmalhaire/xk6-mqtt#24]
Related: https://github.com/pmalhaire/xk6-mqtt/issues/21

Hi, thank you for the extension. I ran into the error in the title after building with the default `xk6 build latest --with github.com/pmalhaire/xk6-mqtt`. I was able to work around by specifying a commit like `xk6 build latest --with github.com/pmalhaire/xk6-mqtt@231ecd388e503ca4a59eb346e03ac8a66011e12e`. I see the latest release was created back in July but the [commit that fixes the issue](https://github.com/pmalhaire/xk6-mqtt/pull/22/files) was made in November so perhaps it's just a matter of creating a new release.

**Comment by clarkbynum** [comment]
My fault, I see that you've listed support for v0.43.1 of k6. For posterity I was able to get the extension working with `xk6 build v0.45.1 --with github.com/pmalhaire/xk6-mqtt`

**Comment by pmalhaire** [comment]
You are right, I fixed this but I did not do a release

**Comment by pmalhaire** [comment]
Release created v0.40.0
