### ISSUE TITLE
Test with many client ids

### ISSUE THREAD

**Issue by ctobolski** [pmalhaire/xk6-mqtt#37]
Hello thank you for your work on this extension, it has been very helpful. Please let me know if this question belongs somewhere else.

My use case for mqtt in k6 is to load test an IoT api where I might have many unique clients. In order to achieve this I think I need to establish the connection within the scenario. The examples currently connect and teardown outside of the scenario function. This required a bit of tweaking to the client module to pass in a client id when using `client.Connect`. 

Have you considered this use case, and do you have any thoughts on how it might be implemented in this library? I wanted to ask before I continue with my forked solution, as this extension is explicitly referenced in the ["Don't build if it is already built"](https://k6.io/docs/extensions/get-started/create/#avoid-unneeded-work) warning 😄 

If you do, I would be happy to help, though the sum total of my go experience has been on modifying what you have here.

**Comment by Alpa-1** [comment]
The way we do this is we create the client in the `init` lifecycle where we pass in the client ID.

We then connect on the first iteration inside the scenario function.

```javascript
import exec from 'k6/execution'

let client = mqtt.Client({
    ["host:port"],
    "username",
    "password",
    false, //clean session
    Math.random() + __VU, // client ID
    20000 // timeout
  );
}

export default function(data) {
  if (exec.vu.iterationInInstance === 0) {
    try {
      client.connect();
    } catch (e) {
      exec.test.abort(`VU ${vuid} failed to connect: ${e}`);
    }
  }
}
```

Does that help?

**Comment by ctobolski** [comment]
Hey thank you, I think I had a fundamental misunderstanding about how the init context works. This was super helpful!
