### ISSUE TITLE
Missing ENV Error

### ISSUE THREAD

**Issue by Spittal** [pmalhaire/xk6-mqtt#39]
Hi there, getting an error when instantiating a new MQTT Client. To reproduce, I build k6 with...

```Dockerfile
FROM grafana/xk6

RUN xk6 build --with github.com/pmalhaire/xk6-mqtt@latest
``` 
Then with that k6 executable I can run the following testing code
```javascript
import { Client } from 'k6/x/mqtt';

export default function () {
  try {
    const mqttPublisher = new Client(
      ['whatever:80'],
      '',
      '',
      false,
      'k6_publisher',
      2000,
    );

    mqttPublisher.connect();
    console.log(`Connected successfully`);
  }
  catch (error: any) {
    console.error(`Error: ${error.message}`);
  }
}
```

I get the following error `GoError: missing env`. I've tracked down the error to https://github.com/pmalhaire/xk6-mqtt/blob/343795c84676942243d493b304420204cfc5a6d9/stats.go#L31 which invokes `vu.InitEnv` which I admit, I don't really understand. All of this is happening either in `setup` or in a normal `vu` execution path. Anyway, any help would be very appreciated.

**Comment by ezeeb** [comment]
I had the same issue. If i remember it correctly, you can call "new Client" only in the init phase. See https://grafana.com/docs/k6/latest/using-k6/test-lifecycle/

**Comment by pmalhaire** [comment]
Yes the client are only created in the init phase see here
https://github.com/pmalhaire/xk6-mqtt/blob/main/examples/test.js#L45
