### ISSUE TITLE
stats package migration

### ISSUE THREAD

**Issue by codebien** [pmalhaire/xk6-mqtt#9]
[k6 v0.38.0](https://github.com/grafana/k6/releases/tag/v0.38.0) has been released and it contains a breaking change for the `stats` package. We merged it in the `metrics` package. The current build of the extension could be affected.

* The fix should migrate all the references of the `stats` package to the relative `metrics` definition. The API is not changed so it should be just a find and replace of the package.
* An upgrade of the k6's go module to v0.38.0 is required.
* A migration to the new module API could be also required info and context are available here https://k6.io/docs/extensions/guides/create-an-extension/#advanced-javascript-extension.

**Comment by pmalhaire** [comment]
@codebien The migration is in wip in https://github.com/pmalhaire/xk6-mqtt/tree/update/0.38.0

**Comment by pmalhaire** [comment]
@codebien migration is done, between I am not sure stats are done the right way

**Comment by pmalhaire** [comment]
Update done
